first attempt at recreating build matrix

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -10,11 +10,29 @@ jobs:
     # TODO: not sure what the best OS to run on is so ubuntu will do for now
     runs-on: ubuntu-latest
 
+    strategy:
+      # Allows running the build multiple times with different configurations
+      matrix:
+        rust: ["stable", "nightly", "beta"]
+        deny_warnings: ['', 1]
+
+        # For nightly rust, run the check-exercises.sh script with DENYWARNINGS=1
+        include:
+          - rust: nightly
+            deny_warnings: 1
+            run: ./_test/check-exercises.sh DENYWARNINGS=${{ matrix.deny_warnings }}
+
+    
+    # Allow failures on nightly rust, or beta if DENYWARNINGS is enabled
+    continue-on-error: ${{ matrix.rust == "nightly || (matrix.rust == "beta" && DENYWARNINGS == 1)}}
+
     steps:
       # Checks out a copy of your repository on the ubuntu-latest machine
       - name: Checkout code
         uses: actions/checkout@v2
-      
+        env: 
+          DENYWARNINGS: ${{ matrix.deny_warnings }}
+
       # run these as steps
       - name: Check exercises
         run: ./_test/check-exercises.sh
